/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PopupSpa = {
  _id: string;
  _type: "popupSpa";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pltitle?: string;
  entitle?: string;
  slug?: Slug;
  plkeyMessage?: string;
  enkeyMessage?: string;
  popupImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isActive?: boolean;
  displayFrom?: string;
  displayTo?: string;
};

export type Popup = {
  _id: string;
  _type: "popup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pltitle?: string;
  entitle?: string;
  slug?: Slug;
  plkeyMessage?: string;
  enkeyMessage?: string;
  popupImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  isActive?: boolean;
  displayFrom?: string;
  displayTo?: string;
};

export type SpaOffer = {
  _id: string;
  _type: "spaOffer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  offerName?: string;
  slug?: Slug;
  offerFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  description?: string;
};

export type BusinessOffer = {
  _id: string;
  _type: "businessOffer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  offerName?: string;
  slug?: Slug;
  offerFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  description?: string;
  offerKey?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventType?: "wesela" | "komunie" | "uroczystosci-rodzinne" | "przyjecia-plenerowe";
  menuName?: string;
  slug?: Slug;
  menuFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  description?: string;
  isActive?: boolean;
  validFrom?: string;
  validUntil?: string;
  displayOrder?: number;
};

export type Menu = {
  _id: string;
  _type: "menu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  restaurant?: "dzika-roza" | "klub-coola" | "bar-przystan";
  menuName?: string;
  slug?: Slug;
  menuFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  description?: string;
  isActive?: boolean;
  validFrom?: string;
  validUntil?: string;
  displayOrder?: number;
};

export type Voucher = {
  _id: string;
  _type: "voucher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  plname?: string;
  enname?: string;
  slug?: Slug;
  voucherImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  pldescription?: string;
  endescription?: string;
  plconditions?: string;
  enconditions?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  entitle?: string;
  slug?: Slug;
  description?: string;
};

export type Offers = {
  _id: string;
  _type: "offers";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  plname?: string;
  subtitle?: string;
  enname?: string;
  ensubtitle?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  price?: number;
  validFrom?: string;
  validUntil?: string;
  daysNights?: string;
  endaysNights?: string;
  meals?: string;
  pldescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  endescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  offerListing?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  offerListingEn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mainAttractions?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mainAttractionsEn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  paidAttractions?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  paidAttractionsEn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  bookingConditions?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  bookingConditionsEn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  practicalInfo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  practicalInfoEn?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  isActive?: boolean;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = PopupSpa | Popup | SpaOffer | BusinessOffer | Event | Menu | Voucher | Category | Offers | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/menus/getEventBySlug.ts
// Variable: EVENTS_BY_TYPE_QUERY
// Query: *[_type == "event" && eventType == $eventType && isActive == true] {            _id,            eventType,            menuName,            slug,            menuFile,            description,            isActive,            validFrom,            validUntil,            displayOrder        } | order(displayOrder asc, menuName asc)
export type EVENTS_BY_TYPE_QUERYResult = Array<{
  _id: string;
  eventType: "komunie" | "przyjecia-plenerowe" | "uroczystosci-rodzinne" | "wesela" | null;
  menuName: string | null;
  slug: Slug | null;
  menuFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
  isActive: boolean | null;
  validFrom: string | null;
  validUntil: string | null;
  displayOrder: number | null;
}>;
// Variable: EVENT_BY_SLUG_QUERY
// Query: *[_type == "event" && slug.current == $slug && isActive == true][0] {            _id,            eventType,            menuName,            slug,            menuFile,            description,            isActive,            validFrom,            validUntil,            displayOrder        }
export type EVENT_BY_SLUG_QUERYResult = {
  _id: string;
  eventType: "komunie" | "przyjecia-plenerowe" | "uroczystosci-rodzinne" | "wesela" | null;
  menuName: string | null;
  slug: Slug | null;
  menuFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
  isActive: boolean | null;
  validFrom: string | null;
  validUntil: string | null;
  displayOrder: number | null;
} | null;
// Variable: ALL_EVENTS_QUERY
// Query: *[_type == "event" && isActive == true] {            _id,            eventType,            menuName,            slug,            menuFile,            description,            isActive,            validFrom,            validUntil,            displayOrder        } | order(eventType asc, displayOrder asc, menuName asc)
export type ALL_EVENTS_QUERYResult = Array<{
  _id: string;
  eventType: "komunie" | "przyjecia-plenerowe" | "uroczystosci-rodzinne" | "wesela" | null;
  menuName: string | null;
  slug: Slug | null;
  menuFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
  isActive: boolean | null;
  validFrom: string | null;
  validUntil: string | null;
  displayOrder: number | null;
}>;

// Source: ./sanity/lib/menus/getMenusByRestaurant.ts
// Variable: MENUS_BY_RESTAURANT_QUERY
// Query: *[_type == "menu" && restaurant == $restaurant && isActive == true] {            _id,            restaurant,            menuName,            slug,            menuFile,            description,            isActive,            validFrom,            validUntil,            displayOrder        } | order(displayOrder asc, menuName asc)
export type MENUS_BY_RESTAURANT_QUERYResult = Array<{
  _id: string;
  restaurant: "bar-przystan" | "dzika-roza" | "klub-coola" | null;
  menuName: string | null;
  slug: Slug | null;
  menuFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
  isActive: boolean | null;
  validFrom: string | null;
  validUntil: string | null;
  displayOrder: number | null;
}>;
// Variable: ALL_MENUS_QUERY
// Query: *[_type == "menu" && isActive == true] {            _id,            restaurant,            menuName,            slug,            menuFile,            description,            isActive,            validFrom,            validUntil,            displayOrder        } | order(restaurant asc, displayOrder asc, menuName asc)
export type ALL_MENUS_QUERYResult = Array<{
  _id: string;
  restaurant: "bar-przystan" | "dzika-roza" | "klub-coola" | null;
  menuName: string | null;
  slug: Slug | null;
  menuFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
  isActive: boolean | null;
  validFrom: string | null;
  validUntil: string | null;
  displayOrder: number | null;
}>;

// Source: ./sanity/lib/offers/getBusinessOffer.ts
// Variable: ALL_BUSINESS_OFFERS_QUERY
// Query: *[_type == "businessOffer"] {      _id,      offerName,      offerKey,      slug,      offerFile,      description    } | order(_createdAt desc)
export type ALL_BUSINESS_OFFERS_QUERYResult = Array<{
  _id: string;
  offerName: string | null;
  offerKey: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
}>;
// Variable: BUSINESS_OFFER_BY_KEY_QUERY
// Query: *[_type == "businessOffer" && offerKey == $offerKey] {      _id,      offerName,      offerKey,      slug,      offerFile,      description    }[0]
export type BUSINESS_OFFER_BY_KEY_QUERYResult = {
  _id: string;
  offerName: string | null;
  offerKey: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
} | null;
// Variable: BUSINESS_OFFER_BY_SLUG_QUERY
// Query: *[_type == "businessOffer" && slug.current == $slug] {      _id,      offerName,      offerKey,      slug,      offerFile,      description    }[0]
export type BUSINESS_OFFER_BY_SLUG_QUERYResult = {
  _id: string;
  offerName: string | null;
  offerKey: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
} | null;
// Variable: BUSINESS_OFFER_BY_NAME_QUERY
// Query: *[_type == "businessOffer" && offerName match $offerName] {      _id,      offerName,      offerKey,      slug,      offerFile,      description    }[0]
export type BUSINESS_OFFER_BY_NAME_QUERYResult = {
  _id: string;
  offerName: string | null;
  offerKey: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
} | null;
// Variable: PRIMARY_BUSINESS_OFFER_QUERY
// Query: *[_type == "businessOffer"] | order(_createdAt desc) [0] {      _id,      offerName,      offerKey,      slug,      offerFile,      description    }
export type PRIMARY_BUSINESS_OFFER_QUERYResult = {
  _id: string;
  offerName: string | null;
  offerKey: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
} | null;

// Source: ./sanity/lib/offers/getOfferBySlug.ts
// Variable: OFFER_BY_ID_QUERY
// Query: *[_type == "offers" && slug.current == $slug && isActive == true] {            _id,            plname,            subtitle,            enname,            ensubtitle,            slug,            image,            price,            validFrom,            validUntil,            daysNights,            endaysNights,            meals,            pldescription,            endescription,            offerListing,            offerListingEn,            mainAttractions,            mainAttractionsEn,            paidAttractions,            paidAttractionsEn,            bookingConditions,            bookingConditionsEn,            practicalInfo,            practicalInfoEn,            isActive,            categories        } | order(plname asc) [0]
export type OFFER_BY_ID_QUERYResult = {
  _id: string;
  plname: string | null;
  subtitle: string | null;
  enname: string | null;
  ensubtitle: string | null;
  slug: Slug | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  price: number | null;
  validFrom: string | null;
  validUntil: string | null;
  daysNights: string | null;
  endaysNights: string | null;
  meals: string | null;
  pldescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  endescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  offerListing: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  offerListingEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mainAttractions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mainAttractionsEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  paidAttractions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  paidAttractionsEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  bookingConditions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  bookingConditionsEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  practicalInfo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  practicalInfoEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  isActive: boolean | null;
  categories: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }> | null;
} | null;

// Source: ./sanity/lib/offers/getOffers.ts
// Variable: ALL_OFFERS_QUERY
// Query: *[_type == "offers" && isActive == true] {      _id,      plname,      subtitle,      enname,      ensubtitle,      slug,      image,      price,      validFrom,      validUntil,      daysNights,      endaysNights,      meals,      pldescription,      endescription,      offerListing,      offerListingEn,      mainAttractions,      mainAttractionsEn,      paidAttractions,      paidAttractionsEn,      bookingConditions,      bookingConditionsEn,      practicalInfo,      practicalInfoEn,      isActive,      orderRank,      "categories": categories[] {        _ref,        _key,        "title": @->title,        "entitle": @->entitle,         "pltitle": @->pltitle      }    } | order(orderRank)
export type ALL_OFFERS_QUERYResult = Array<{
  _id: string;
  plname: string | null;
  subtitle: string | null;
  enname: string | null;
  ensubtitle: string | null;
  slug: Slug | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  price: number | null;
  validFrom: string | null;
  validUntil: string | null;
  daysNights: string | null;
  endaysNights: string | null;
  meals: string | null;
  pldescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  endescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  offerListing: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  offerListingEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mainAttractions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mainAttractionsEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  paidAttractions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  paidAttractionsEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  bookingConditions: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  bookingConditionsEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  practicalInfo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  practicalInfoEn: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  isActive: boolean | null;
  orderRank: string | null;
  categories: Array<{
    _ref: string;
    _key: string;
    title: string | null;
    entitle: string | null;
    pltitle: null;
  }> | null;
}>;

// Source: ./sanity/lib/offers/getSpaOffer.ts
// Variable: ALL_SPA_OFFERS_QUERY
// Query: *[_type == "spaOffer"] {      _id,      offerName,      slug,      offerFile,      description    } | order(_createdAt desc)
export type ALL_SPA_OFFERS_QUERYResult = Array<{
  _id: string;
  offerName: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
}>;
// Variable: SPA_OFFER_BY_SLUG_QUERY
// Query: *[_type == "spaOffer" && slug.current == $slug] {      _id,      offerName,      slug,      offerFile,      description    }[0]
export type SPA_OFFER_BY_SLUG_QUERYResult = {
  _id: string;
  offerName: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
} | null;
// Variable: PRIMARY_SPA_OFFER_QUERY
// Query: *[_type == "spaOffer"] | order(_createdAt desc) [0] {      _id,      offerName,      slug,      offerFile,      description    }
export type PRIMARY_SPA_OFFER_QUERYResult = {
  _id: string;
  offerName: string | null;
  slug: Slug | null;
  offerFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  description: string | null;
} | null;

// Source: ./sanity/lib/offers/getVoucherBySlug.ts
// Variable: VOUCHER_BY_SLUG_QUERY
// Query: *[_type == "voucher" && slug.current == $slug][0] {      _id,      plname,      enname,      slug,      voucherImage,      pldescription,      endescription,      plconditions,      enconditions    }
export type VOUCHER_BY_SLUG_QUERYResult = {
  _id: string;
  plname: string | null;
  enname: string | null;
  slug: Slug | null;
  voucherImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  pldescription: string | null;
  endescription: string | null;
  plconditions: string | null;
  enconditions: string | null;
} | null;

// Source: ./sanity/lib/offers/getVouchers.ts
// Variable: ALL_VOUCHERS_QUERY
// Query: *[_type == "voucher"] {      _id,      plname,      enname,      slug,      voucherImage,      pldescription,      endescription,      plconditions,      enconditions    } | order(_createdAt desc)
export type ALL_VOUCHERS_QUERYResult = Array<{
  _id: string;
  plname: string | null;
  enname: string | null;
  slug: Slug | null;
  voucherImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  pldescription: string | null;
  endescription: string | null;
  plconditions: string | null;
  enconditions: string | null;
}>;

// Source: ./sanity/lib/popups/getPopups.ts
// Variable: ACTIVE_POPUPS_QUERY
// Query: *[_type == "popup" && isActive == true && (            (!defined(displayFrom) && !defined(displayTo)) ||            (!defined(displayFrom) && displayTo > now()) ||            (!defined(displayTo) && displayFrom <= now()) ||            (displayFrom <= now() && displayTo > now())        )] {            _id,            pltitle,            entitle,            slug,            plkeyMessage,            enkeyMessage,            popupImage,            isActive,            displayFrom,            displayTo        } | order(_createdAt desc)
export type ACTIVE_POPUPS_QUERYResult = Array<{
  _id: string;
  pltitle: string | null;
  entitle: string | null;
  slug: Slug | null;
  plkeyMessage: string | null;
  enkeyMessage: string | null;
  popupImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isActive: boolean | null;
  displayFrom: string | null;
  displayTo: string | null;
}>;
// Variable: ALL_POPUPS_QUERY
// Query: *[_type == "popup"] {            _id,            pltitle,            entitle,            slug,            plkeyMessage,            enkeyMessage,            popupImage,            isActive,            displayFrom,            displayTo        } | order(_createdAt desc)
export type ALL_POPUPS_QUERYResult = Array<{
  _id: string;
  pltitle: string | null;
  entitle: string | null;
  slug: Slug | null;
  plkeyMessage: string | null;
  enkeyMessage: string | null;
  popupImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isActive: boolean | null;
  displayFrom: string | null;
  displayTo: string | null;
}>;

// Source: ./sanity/lib/popups/getSpaPopup.ts
// Variable: ALL_SPA_POPUPS_QUERY
// Query: *[_type == "popupSpa"] {      _id,      pltitle,      entitle,      slug,      plkeyMessage,      enkeyMessage,      popupImage,      isActive,      displayFrom,      displayTo    } | order(_createdAt desc)
export type ALL_SPA_POPUPS_QUERYResult = Array<{
  _id: string;
  pltitle: string | null;
  entitle: string | null;
  slug: Slug | null;
  plkeyMessage: string | null;
  enkeyMessage: string | null;
  popupImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isActive: boolean | null;
  displayFrom: string | null;
  displayTo: string | null;
}>;
// Variable: ACTIVE_SPA_POPUPS_QUERY
// Query: *[_type == "popupSpa" && isActive == true && (displayFrom <= now() || !defined(displayFrom)) && (displayTo >= now() || !defined(displayTo))] {      _id,      pltitle,      entitle,      slug,      plkeyMessage,      enkeyMessage,      popupImage,      isActive,      displayFrom,      displayTo    } | order(_createdAt desc)
export type ACTIVE_SPA_POPUPS_QUERYResult = Array<{
  _id: string;
  pltitle: string | null;
  entitle: string | null;
  slug: Slug | null;
  plkeyMessage: string | null;
  enkeyMessage: string | null;
  popupImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isActive: boolean | null;
  displayFrom: string | null;
  displayTo: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n        *[_type == \"event\" && eventType == $eventType && isActive == true] {\n            _id,\n            eventType,\n            menuName,\n            slug,\n            menuFile,\n            description,\n            isActive,\n            validFrom,\n            validUntil,\n            displayOrder\n        } | order(displayOrder asc, menuName asc)": EVENTS_BY_TYPE_QUERYResult;
    "\n        *[_type == \"event\" && slug.current == $slug && isActive == true][0] {\n            _id,\n            eventType,\n            menuName,\n            slug,\n            menuFile,\n            description,\n            isActive,\n            validFrom,\n            validUntil,\n            displayOrder\n        }": EVENT_BY_SLUG_QUERYResult;
    "\n        *[_type == \"event\" && isActive == true] {\n            _id,\n            eventType,\n            menuName,\n            slug,\n            menuFile,\n            description,\n            isActive,\n            validFrom,\n            validUntil,\n            displayOrder\n        } | order(eventType asc, displayOrder asc, menuName asc)": ALL_EVENTS_QUERYResult;
    "\n        *[_type == \"menu\" && restaurant == $restaurant && isActive == true] {\n            _id,\n            restaurant,\n            menuName,\n            slug,\n            menuFile,\n            description,\n            isActive,\n            validFrom,\n            validUntil,\n            displayOrder\n        } | order(displayOrder asc, menuName asc)": MENUS_BY_RESTAURANT_QUERYResult;
    "\n        *[_type == \"menu\" && isActive == true] {\n            _id,\n            restaurant,\n            menuName,\n            slug,\n            menuFile,\n            description,\n            isActive,\n            validFrom,\n            validUntil,\n            displayOrder\n        } | order(restaurant asc, displayOrder asc, menuName asc)": ALL_MENUS_QUERYResult;
    "*[_type == \"businessOffer\"] {\n      _id,\n      offerName,\n      offerKey,\n      slug,\n      offerFile,\n      description\n    } | order(_createdAt desc)": ALL_BUSINESS_OFFERS_QUERYResult;
    "*[_type == \"businessOffer\" && offerKey == $offerKey] {\n      _id,\n      offerName,\n      offerKey,\n      slug,\n      offerFile,\n      description\n    }[0]": BUSINESS_OFFER_BY_KEY_QUERYResult;
    "*[_type == \"businessOffer\" && slug.current == $slug] {\n      _id,\n      offerName,\n      offerKey,\n      slug,\n      offerFile,\n      description\n    }[0]": BUSINESS_OFFER_BY_SLUG_QUERYResult;
    "*[_type == \"businessOffer\" && offerName match $offerName] {\n      _id,\n      offerName,\n      offerKey,\n      slug,\n      offerFile,\n      description\n    }[0]": BUSINESS_OFFER_BY_NAME_QUERYResult;
    "*[_type == \"businessOffer\"] | order(_createdAt desc) [0] {\n      _id,\n      offerName,\n      offerKey,\n      slug,\n      offerFile,\n      description\n    }": PRIMARY_BUSINESS_OFFER_QUERYResult;
    "\n        *[_type == \"offers\" && slug.current == $slug && isActive == true] {\n            _id,\n            plname,\n            subtitle,\n            enname,\n            ensubtitle,\n            slug,\n            image,\n            price,\n            validFrom,\n            validUntil,\n            daysNights,\n            endaysNights,\n            meals,\n            pldescription,\n            endescription,\n            offerListing,\n            offerListingEn,\n            mainAttractions,\n            mainAttractionsEn,\n            paidAttractions,\n            paidAttractionsEn,\n            bookingConditions,\n            bookingConditionsEn,\n            practicalInfo,\n            practicalInfoEn,\n            isActive,\n            categories\n        } | order(plname asc) [0]": OFFER_BY_ID_QUERYResult;
    "*[_type == \"offers\" && isActive == true] {\n      _id,\n      plname,\n      subtitle,\n      enname,\n      ensubtitle,\n      slug,\n      image,\n      price,\n      validFrom,\n      validUntil,\n      daysNights,\n      endaysNights,\n      meals,\n      pldescription,\n      endescription,\n      offerListing,\n      offerListingEn,\n      mainAttractions,\n      mainAttractionsEn,\n      paidAttractions,\n      paidAttractionsEn,\n      bookingConditions,\n      bookingConditionsEn,\n      practicalInfo,\n      practicalInfoEn,\n      isActive,\n      orderRank,\n      \"categories\": categories[] {\n        _ref,\n        _key,\n        \"title\": @->title,\n        \"entitle\": @->entitle, \n        \"pltitle\": @->pltitle\n      }\n    } | order(orderRank)": ALL_OFFERS_QUERYResult;
    "*[_type == \"spaOffer\"] {\n      _id,\n      offerName,\n      slug,\n      offerFile,\n      description\n    } | order(_createdAt desc)": ALL_SPA_OFFERS_QUERYResult;
    "*[_type == \"spaOffer\" && slug.current == $slug] {\n      _id,\n      offerName,\n      slug,\n      offerFile,\n      description\n    }[0]": SPA_OFFER_BY_SLUG_QUERYResult;
    "*[_type == \"spaOffer\"] | order(_createdAt desc) [0] {\n      _id,\n      offerName,\n      slug,\n      offerFile,\n      description\n    }": PRIMARY_SPA_OFFER_QUERYResult;
    "*[_type == \"voucher\" && slug.current == $slug][0] {\n      _id,\n      plname,\n      enname,\n      slug,\n      voucherImage,\n      pldescription,\n      endescription,\n      plconditions,\n      enconditions\n    }": VOUCHER_BY_SLUG_QUERYResult;
    "*[_type == \"voucher\"] {\n      _id,\n      plname,\n      enname,\n      slug,\n      voucherImage,\n      pldescription,\n      endescription,\n      plconditions,\n      enconditions\n    } | order(_createdAt desc)": ALL_VOUCHERS_QUERYResult;
    "\n        *[_type == \"popup\" && isActive == true && (\n            (!defined(displayFrom) && !defined(displayTo)) ||\n            (!defined(displayFrom) && displayTo > now()) ||\n            (!defined(displayTo) && displayFrom <= now()) ||\n            (displayFrom <= now() && displayTo > now())\n        )] {\n            _id,\n            pltitle,\n            entitle,\n            slug,\n            plkeyMessage,\n            enkeyMessage,\n            popupImage,\n            isActive,\n            displayFrom,\n            displayTo\n        } | order(_createdAt desc)": ACTIVE_POPUPS_QUERYResult;
    "\n        *[_type == \"popup\"] {\n            _id,\n            pltitle,\n            entitle,\n            slug,\n            plkeyMessage,\n            enkeyMessage,\n            popupImage,\n            isActive,\n            displayFrom,\n            displayTo\n        } | order(_createdAt desc)": ALL_POPUPS_QUERYResult;
    "*[_type == \"popupSpa\"] {\n      _id,\n      pltitle,\n      entitle,\n      slug,\n      plkeyMessage,\n      enkeyMessage,\n      popupImage,\n      isActive,\n      displayFrom,\n      displayTo\n    } | order(_createdAt desc)": ALL_SPA_POPUPS_QUERYResult;
    "*[_type == \"popupSpa\" && isActive == true && (displayFrom <= now() || !defined(displayFrom)) && (displayTo >= now() || !defined(displayTo))] {\n      _id,\n      pltitle,\n      entitle,\n      slug,\n      plkeyMessage,\n      enkeyMessage,\n      popupImage,\n      isActive,\n      displayFrom,\n      displayTo\n    } | order(_createdAt desc)": ACTIVE_SPA_POPUPS_QUERYResult;
  }
}
